plugin: aws_ec2
regions:
  - us-east-1
  - us-west-2
  - eu-west-1
boto_profile: default
keyed_groups:
  - key: tags.Environment
    prefix: env
  - key: placement.availability_zone
    prefix: az
filters:
  instance-state-name: running
compose:
  ansible_host: public_ip_address
  aws_account_id: owner_id