# playbooks/disk-monitoring.yml
---
- name: Multi-Account Disk Utilization Monitoring
  hosts: localhost
  gather_facts: false
  vars:
    aws_accounts:
      - account_id: "111111111111"
        role_name: "AnsibleDiskMonitoringRole"
        regions: ["us-east-1", "us-west-2"]
      - account_id: "222222222222"
        role_name: "AnsibleDiskMonitoringRole"
        regions: ["us-east-1", "eu-west-1"]
      - account_id: "333333333333"
        role_name: "AnsibleDiskMonitoringRole"
        regions: ["us-west-2", "ap-southeast-1"]
    
  tasks:
    - name: Collect disk utilization from all accounts
      include_tasks: tasks/collect_disk_metrics.yml
      loop: "{{ aws_accounts }}"
      loop_control:
        loop_var: account

    - name: Aggregate and store results
      include_tasks: tasks/aggregate_results.yml