- name: Onboard new AWS account
  hosts: localhost
  vars_prompt:
    - name: new_account_id
      prompt: "Enter new AWS account ID"
    - name: account_regions
      prompt: "Enter regions (comma-separated)"
  
  tasks:
    - name: Create cross-account role
      amazon.aws.iam_role:
        name: DiskMonitoringTargetRole
        assume_role_policy_document: "{{ lookup('file', 'target-role-trust-policy.json') }}"
        state: present
      delegate_to: "{{ new_account_id }}"
    
    - name: Update inventory configuration
      lineinfile:
        path: inventory/aws_accounts.yml
        line: |
          - account_id: "{{ new_account_id }}"
            role_name: "DiskMonitoringTargetRole"
            regions: {{ account_regions.split(',') }}